name: bm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: any
  flutter_map_location_marker: any
  permission_handler: ^11.3.1
  android_intent_plus: ^5.1.0
  google_fonts: any
  material_floating_search_bar_2: any
  latlong2: any
  shared_preferences: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/boston.png
    - assets/images/nyc.png
    - assets/images/auck.png


  fonts:
    - family: Ndot
      fonts:
        - asset: assets/fonts/ndot47.ttf
          weight: 400